global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "worker"
    static_configs:
      - targets: ["worker:9100"]

  - job_name: "ai_enricher"
    static_configs:
      - targets: ["ai_enricher:9102"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis_exporter:9121"]

  - job_name: "mongodb_exporter"
    static_configs:
      - targets: ["mongodb_exporter:9216"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
