global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs: [{ targets: ["prometheus:9090"] }]
  - job_name: worker
    static_configs: [{ targets: ["worker:9100"] }]
  - job_name: ai_enricher
    static_configs: [{ targets: ["ai_enricher:9102"] }]
  - job_name: collector_mongo
    static_configs: [{ targets: ["collector_mongo:9101"] }]
  - job_name: collector_s3
    static_configs: [{ targets: ["collector_s3:9103"] }]
  - job_name: collector_embed
    static_configs: [{ targets: ["collector_embed:9104"] }]
